name: Danger Python CI

on:
  pull_request:
    branches:
      - master

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Use a supported version of Node.js

      - name: Install Danger JS
        run: npm install -g danger  # Install danger-js globally

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python Dependencies
        run: pip install danger-python

      - name: Run Danger Python
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: danger-python ci  # Run danger-python CI

      - name: Run Danger Python (if JSON output needed)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: danger-python ci --json > danger_output.json
