name: Danger Python

on:
  pull_request:
    branches:
      - master  # Runs only when a PR targets the master branch

jobs:
  danger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4  # Clones the repo

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Danger JS (Required for Danger Python)
        run: npm install -g danger

      - name: Install Dependencies
        run: pip install danger-python

      - name: Run Danger JS (Generates JSON)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: danger ci --json > danger_output.json

      - name: Run Danger Python (Uses JSON)
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GH_TOKEN }}
        run: danger-python run --json danger_output.json
